import Footer from '@/components/widgets/footer'
import Header from '@/components/widgets/header'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} px-3 mx-auto max-w-[1200px]`}>
				<Header />

				{children}
				<Toaster richColors />

				{/* <Footer /> */}
			</body>
		</html>
	)
}
